#!/bin/bash

set -e
set -x

SOURCE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pushd libuv-1.9.1
./gyp_uv.py -f make
BUILDTYPE=Release make -C out
popd

cmake $SOURCE_DIR
make all VERBOSE=1
